version: '3.5'

services:
  frontend:
    build:
      context: ./frontend
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - my_network
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd app; pytest; uvicorn main:app --host 0.0.0.0'
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/book_tracker
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=book_tracker
    networks:
      - my_network

volumes:
  postgres_data:


networks:
  my_network:
